const blogs = [
  {
    id: 1,
    title: "Boost Business Efficiency",
    slug: "boost-business-efficiency",
    excerpt:
      "Want to boost your business efficiency. Try automating repetitive tasks, outsourcing non-core activities, and implementing an agile process.",
    image: "/images/blog/7.png",
    tag: "Analysis",
    tagStyle: "blog__meta-tag--style1",
    author: "Gazali Oztepe",
    authorImage: "/images/blog/author/1.png",
    date: "Sep 27, 2023",
  },
  {
    id: 2,
    title: "Avoiding Business Mistakes",
    slug: "avoiding-business-mistakes",
    excerpt:
      "We all make mistakes, but in business they can be costly. So, do your research, make a plan, and don't forget to double-check everything.",
    image: "/images/blog/8.png",
    tag: "Research",
    tagStyle: "blog__meta-tag--style2",
    author: "Yilmaz Orhan",
    authorImage: "/images/blog/author/2.png",
    date: "May 20, 2023",
  },
  {
    id: 3,
    title: "Essential for Small Business",
    slug: "essential-for-small-business",
    excerpt:
      "Running a small business requires hard work, but don't forget the essentials: a solid business plan, reliable team, and great communication skills!",
    image: "/images/blog/9.png",
    tag: "Management",
    tagStyle: "blog__meta-tag--style2",
    author: "Huseyin Akcagul",
    authorImage: "/images/blog/author/3.png",
    date: "May 16, 2023",
  },
  {
    id: 4,
    title: "Business Plans Strategies",
    slug: "business-plans-strategies",
    excerpt:
      "When it comes to business plans, don't forget to set realistic goals, stay adaptable, and always keep your customer in mind.",
    image: "/images/blog/10.png",
    tag: "Leadership",
    tagStyle: "blog__meta-tag--style2",
    author: "Senturk Yasar",
    authorImage: "/images/blog/author/4.png",
    date: "Mar 25, 2023",
  },
  {
    id: 5,
    title: "Maximizing Business Profit",
    slug: "maximizing-business-profit",
    excerpt:
      "Alright guys, if we want to make more money, we need to maximize profits. Cut unnecessary costs and increase smart sales strategies.",
    image: "/images/blog/11.png",
    tag: "Business",
    tagStyle: "blog__meta-tag--style1",
    author: "Muazzez Yasar",
    authorImage: "/images/blog/author/5.png",
    date: "May 29, 2023",
  },
  {
    id: 6,
    title: "Strong Brand Identities",
    slug: "strong-brand-identities",
    excerpt:
      "Brand identities are like superhero capes. They help businesses stand out, communicate values, and build long-term trust.",
    image: "/images/blog/12.png",
    tag: "Mentoring",
    tagStyle: "blog__meta-tag--style1",
    author: "Sevil Haslak",
    authorImage: "/images/blog/author/6.png",
    date: "May 14, 2023",
  },
  {
    id: 7,
    title: "Market Research Insight",
    slug: "market-research-insight",
    excerpt:
      "Market research is crucial for any business. It helps understand customer behavior and supports better strategic decisions.",
    image: "/images/blog/13.png",
    tag: "Workshop",
    tagStyle: "blog__meta-tag--style2",
    author: "Ayse Nuriye Ertas",
    authorImage: "/images/blog/author/7.png",
    date: "Aug 27, 2023",
  },
  {
    id: 8,
    title: "Build Successful Business",
    slug: "build-successful-business",
    excerpt:
      "Building a successful business takes hard work, dedication, and the right mindset. With consistency, success follows.",
    image: "/images/blog/14.png",
    tag: "Training",
    tagStyle: "blog__meta-tag--style1",
    author: "Gulnaz Dagli",
    authorImage: "/images/blog/author/8.png",
    date: "Aug 28, 2023",
  },
  {
    id: 9,
    title: "Business for Women",
    slug: "business-for-women",
    excerpt:
      "Starting a business is tough, but women have proven time and again they can lead, innovate, and succeed in entrepreneurship.",
    image: "/images/blog/15.png",
    tag: "Leadership",
    tagStyle: "blog__meta-tag--style2",
    author: "Avni Evran",
    authorImage: "/images/blog/author/1.png",
    date: "Apr 09, 2023",
  },
];

export default blogs;
